name: build-doc

on: [push]

jobs:

  build-doc-IEC61970_16v29a:
    runs-on: ubuntu-latest
    env:
      USE_CIM_VERSION: IEC61970_16v29a
    steps:
    - uses: actions/checkout@v2    
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install Doxygen
      run: sudo apt-get install doxygen 
      shell: bash 
    - name: Install Xerces-C
      run: sudo apt install libxerces-c-dev
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}}
      
    - name: Configure CMake and compile
      shell: bash
      working-directory: ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}}/
      run: |
          cd ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}} 
          cmake ../.. -DUSE_CIM_VERSION=${{env.USE_CIM_VERSION}}
          make doc
    - uses: actions/upload-artifact@v2
      with:
        name: doc_${{env.USE_CIM_VERSION}}
        path: ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}}/doc/html
        retention-days: 90



  build-doc-IEC61970_17v07:
    runs-on: ubuntu-latest
    env:
      USE_CIM_VERSION: IEC61970_17v07
    steps:
    - uses: actions/checkout@v2    
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install Doxygen
      run: sudo apt-get install doxygen 
      shell: bash 
    - name: Install Xerces-C
      run: sudo apt install libxerces-c-dev
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}}
      
    - name: Configure CMake and compile
      shell: bash
      working-directory: ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}}/
      run: |
          cd ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}} 
          cmake ../.. -DUSE_CIM_VERSION=${{env.USE_CIM_VERSION}}
          make doc
    - uses: actions/upload-artifact@v2
      with:
        name: doc_${{env.USE_CIM_VERSION}}
        path: ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}}/doc/html

  build-doc-IEC61970_16v29a_IEC61968_12v08:
    runs-on: ubuntu-latest
    env:
      USE_CIM_VERSION: IEC61970_16v29a_IEC61968_12v08
    steps:
    - uses: actions/checkout@v2    
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install Doxygen
      run: sudo apt-get install doxygen 
      shell: bash 
    - name: Install Xerces-C
      run: sudo apt install libxerces-c-dev
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}}
      
    - name: Configure CMake and compile
      shell: bash
      working-directory: ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}}/
      run: |
          cd ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}} 
          cmake ../.. -DUSE_CIM_VERSION=${{env.USE_CIM_VERSION}}
          make doc
    - uses: actions/upload-artifact@v2
      with:
        name: doc_${{env.USE_CIM_VERSION}}
        path: ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}}/doc/html


  build-doc-CGMES_2-4-15_27JAN2020:
    runs-on: ubuntu-latest
    env:
      USE_CIM_VERSION: CGMES_2.4.15_27JAN2020
    steps:
    - uses: actions/checkout@v2    
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install Doxygen
      run: sudo apt-get install doxygen 
      shell: bash 
    - name: Install Xerces-C
      run: sudo apt install libxerces-c-dev
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}}
      
    - name: Configure CMake and compile
      shell: bash
      working-directory: ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}}/
      run: |
          cd ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}} 
          cmake ../.. -DUSE_CIM_VERSION=${{env.USE_CIM_VERSION}}
          make doc
    - uses: actions/upload-artifact@v2
      with:
        name: doc_${{env.USE_CIM_VERSION}}
        path: ${{runner.workspace}}/libcimpp/build/${{env.USE_CIM_VERSION}}/doc/html



